export const TOGGLE_SEARCH_MODAL = "TOGGLE_SEARCH_MODAL";

export const GET_WEATHER_BY_POSITION = "GET_WEATHER_BY_POSITION";

export const GET_WEATHER_BY_NAME = "GET_WEATHER_BY_NAME";

export const SHOW_LOADING_INDICATOR = "SHOW_LOADING_INDICATOR";

export const NOT_FOUND = "NOT_FOUND";
